
on:
  push:
    branches:
      - master

name: Deploy to Amazon EKS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAIGSAOJWSEJ2AHCIQ
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: pod kubctl version
      run: |
       kubectl version --client=true \ 
       pwd 
       
    - name: pod apply
      run: |
       aws eks --region us-east-2 update-kubeconfig --name Cluster-demo &&
       kubectl config view && kubectl get svc && mkdir -p ~/.kube && kubectl apply -f https://k8s.io/examples/application/deployment.yaml && kubectl describe deployment nginx-deployment && kubectl get pods -l app=nginx
 
       
    - name: Dormir por 3 minutos
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    
    - name: Crear node-group
      
      run: |
       aws eks create-nodegroup --cluster-name=pdaaasfvr --nodegroup-name=pepe --subnets=subnet-05226b7df7a7f93a7 --node-role=arn:aws:iam::343942719020:role/Clave-valor
