
on:
  push:
    branches:
      - master

name: Deploy to Amazon EKS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAIGSAOJWSEJ2AHCIQ
        aws-secret-access-key: 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
        aws-region: us-east-2

    - name: Deploy k8s yaml

      run: |
        aws eks create-cluster --name pr \
        --role-arn arn:aws:iam::343942719020:role/Cluster_uno \
        --resources-vpc-config subnetIds=subnet-05226b7df7a7f93a7,subnet-092acba3f13e38833,securityGroupIds=sg-0512fccb0fe05efd6
    - name: pod
      run: |
       kubectl wait --namespace ingress-nginx \ 
       --for=condition=ready pod \
       --selector=app.kubernetes.io/component=controller \ 
       --timeout=90s
       
    - name: Dormir por 3 minutos
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    
    - name: Crear node-group
      
      run: |
       aws eks create-nodegroup --cluster-name=pr --nodegroup-name=pepe --subnets=subnet-05226b7df7a7f93a7 --node-role=arn:aws:iam::343942719020:role/Clave-valor
