
on:
  push:
    branches:
      - master

name: Deploy to Amazon EKS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIATPZP3QVYSXK5UOPW
        aws-secret-access-key: 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
        aws-region: us-east-2
    - name: Deploy k8s yaml

      
    - name: pod kubctl version
      run: |
       kubectl version --client=true \ 
       pwd 

    - name: Dormir por 3 minutos
      uses: jakejarvis/wait-action@master
      with:
        time: '40s'
    
       
    - name: pod apply
      run: |
       aws eks --region us-east-2 update-kubeconfig --name Cluster-demo &&
       kubectl config view && kubectl get svc && mkdir -p ~/.kube && kubectl apply -f ./deployment.yaml && kubectl describe deployment nginx-deployment && kubectl get pods -l app=nginx
 
    - name: pelea
      run: |
       kubectl describe deployment nginx-deployment && kubectl get pods -l app=nginx && kubectl --kubeconfig ./kubeconfig expose deployment/my-nginx \
       --port=80 --target-port=80 \
       --name=my-nginx-service --type=LoadBalancer
    - name: Crear node-group
      
      run: |
       aws eks create-nodegroup --cluster-name=Cluster-d --nodegroup-name=pep --subnets=subnet-03c011d8e59dadebc --node-role=arn:aws:iam::240081667441:role/Bebe
